version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
    ports:
      - '5432:5432'
    networks:
      - backend-net

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    healthcheck:
      disable: true
    depends_on:
      - postgres
      - redis
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
    name: services_net